package companion

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"testing"
	"time"
)

// vectors is taw-hub's docs/reference/hub-signing-vectors.json, the source of
// truth for the wire protocol (generated by the Hub, checked by the companion).
type vectors struct {
	Keys map[string]struct {
		KeyID   string `json:"key_id"`
		Public  string `json:"public_key_b64"`
		Secret  string `json:"secret_key_b64"`
		SeedHex string `json:"seed_hex"`
	} `json:"keys"`
	Vectors []struct {
		Name      string            `json:"name"`
		Algo      string            `json:"algo"`
		KeyID     string            `json:"key_id"`
		Method    string            `json:"method"`
		Path      string            `json:"path"`
		Timestamp int64             `json:"timestamp"`
		Nonce     string            `json:"nonce"`
		Body      string            `json:"body"`
		Canonical string            `json:"canonical_string"`
		Signature string            `json:"signature_b64"`
		Headers   map[string]string `json:"headers"`
		Expect    string            `json:"expect"`
	} `json:"vectors"`
}

func load(t *testing.T) vectors {
	t.Helper()
	data, err := os.ReadFile("testdata/hub-signing-vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var v vectors
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func TestVectors(t *testing.T) {
	v := load(t)
	hub, err := ParseKey(v.Keys["hub_ed25519"].KeyID, v.Keys["hub_ed25519"].Secret)
	if err != nil {
		t.Fatal(err)
	}
	site, err := ParseKey(v.Keys["site_ed25519"].KeyID, v.Keys["site_ed25519"].Secret)
	if err != nil {
		t.Fatal(err)
	}
	if hub.Public() != v.Keys["hub_ed25519"].Public || site.Public() != v.Keys["site_ed25519"].Public {
		t.Fatal("public halves don't match the vectors")
	}
	pinned := SiteKey{ID: site.ID, Public: site.Public()}
	ran := 0
	for _, vec := range v.Vectors {
		if vec.Algo != "ed25519" {
			continue // HMAC is the n8n channel; taw-fleet doesn't use it
		}
		ran++
		got := Canonical(vec.Method, vec.Path, vec.Timestamp, vec.Nonce, []byte(vec.Body))
		if vec.Expect == "valid" && got != vec.Canonical {
			t.Errorf("%s: canonical\n got %q\nwant %q", vec.Name, got, vec.Canonical)
		}
		if vec.Method == "RESPONSE" {
			h := http.Header{}
			for k, val := range vec.Headers {
				h.Set(k, val)
			}
			if vec.KeyID != site.ID {
				continue // response_enrol is signed by the Hub, not a site
			}
			err := VerifyResponse(h, vec.Path, []byte(vec.Body), pinned, time.Unix(vec.Timestamp, 0))
			if (err == nil) != (vec.Expect == "valid") {
				t.Errorf("%s: verify = %v, expect %s", vec.Name, err, vec.Expect)
			}
			continue
		}
		h := http.Header{}
		hub.Sign(h, vec.Method, vec.Path, vec.Timestamp, vec.Nonce, []byte(vec.Body))
		sigOK := h.Get(HeaderSignature) == vec.Signature
		if vec.Expect == "valid" {
			if !sigOK {
				t.Errorf("%s: signature\n got %s\nwant %s", vec.Name, h.Get(HeaderSignature), vec.Signature)
			}
			for k, want := range vec.Headers {
				if h.Get(k) != want {
					t.Errorf("%s: header %s = %q, want %q", vec.Name, k, h.Get(k), want)
				}
			}
		} else if sigOK {
			t.Errorf("%s: a tampered body must not produce the vector's signature", vec.Name)
		}
	}
	if ran < 7 {
		t.Errorf("only %d ed25519 vectors ran", ran)
	}
}

func TestVerifyResponseRejects(t *testing.T) {
	v := load(t)
	site, _ := ParseKey(v.Keys["site_ed25519"].KeyID, v.Keys["site_ed25519"].Secret)
	pinned := SiteKey{ID: site.ID, Public: site.Public()}
	body := []byte(`{"ok":true}`)
	now := time.Unix(1788134400, 0)
	signed := func() http.Header {
		h := http.Header{}
		site.Sign(h, "RESPONSE", "/wp-json/taw-hub/v1/health", now.Unix(), "nonce-123456", body)
		return h
	}
	if err := VerifyResponse(signed(), "/wp-json/taw-hub/v1/health", body, pinned, now); err != nil {
		t.Fatalf("good: %v", err)
	}
	cases := []struct {
		name string
		h    http.Header
		path string
		body []byte
		pin  SiteKey
		now  time.Time
		want error
	}{
		{"unsigned", http.Header{}, "/wp-json/taw-hub/v1/health", body, pinned, now, ErrUnsigned},
		{"tampered body", signed(), "/wp-json/taw-hub/v1/health", []byte(`{"ok":false}`), pinned, now, ErrBadSignature},
		{"other path", signed(), "/wp-json/taw-hub/v1/logs", body, pinned, now, ErrBadSignature},
		{"key changed", signed(), "/wp-json/taw-hub/v1/health", body, SiteKey{ID: "site-other", Public: pinned.Public}, now, ErrKeyChanged},
		{"stale", signed(), "/wp-json/taw-hub/v1/health", body, pinned, now.Add(2 * time.Minute), ErrStale},
	}
	for _, c := range cases {
		if err := VerifyResponse(c.h, c.path, c.body, c.pin, c.now); !errors.Is(err, c.want) {
			t.Errorf("%s: err = %v, want %v", c.name, err, c.want)
		}
	}
}

func TestParseKey(t *testing.T) {
	v := load(t)
	k, err := ParseKey("hub-local", v.Keys["hub_ed25519"].Secret)
	if err != nil {
		t.Fatal(err)
	}
	seed := base64.StdEncoding.EncodeToString(k.Private.Seed())
	if k2, err := ParseKey("hub-local", seed); err != nil || k2.Public() != k.Public() {
		t.Errorf("seed form: %v", err)
	}
	if _, err := ParseKey("x", "c2hvcnQ="); err == nil {
		t.Error("short key")
	}
	bad := append([]byte(nil), k.Private...)
	bad[40] ^= 1
	if _, err := ParseKey("x", base64.StdEncoding.EncodeToString(bad)); err == nil {
		t.Error("mismatched halves")
	}
	if a, b := NewNonce(), NewNonce(); len(a) != 32 || a == b {
		t.Error("nonce")
	}
}
